version: '3'
services:
  web:
    image: nginx:latest
    ports: 
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/app
  php:
    build:
      context: .
      dockerfile: PHP_Dockerfile
    volumes:
      - ./src:/app
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal